name: Unit test

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  unit_test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.9']

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: pip3 install -r requirements.txt
    
    - name: Run tests
      run: python3 tests/tester.py
