name: Unit test

on:
  push:
    branches:
    - main
    paths:
    - main.py
    - requirements.txt
    - .github/workflows/unit_test.yml
    - modules/**
    - samples/**
    - tests/**
  pull_request:
    branches:
    - main
    paths:
    - main.py
    - requirements.txt
    - .github/workflows/unit_test.yml
    - modules/**
    - samples/**
    - tests/**

jobs:
  unit_test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.9']

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: pip3 install -r requirements.txt

    - name: Run test (1)
      run: python3 tests/tester_01.py

    - name: Run test (2)
      run: python3 tests/tester_02.py

    - name: Run test (3)
      run: python3 tests/tester_03.py

    - name: Run test (4)
      run: python3 tests/tester_04.py
