name: verify

on:
  push:
    branches:
    - main
    paths:
    - main.py
    - requirements.txt
    - .github/workflows/**
    - modules/**
    - samples/**
    - verify/**
  pull_request:
    branches:
    - main
    paths:
    - main.py
    - requirements.txt
    - .github/workflows/**
    - modules/**
    - samples/**
    - verify/**

jobs:
  verify:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
      pip3 install -r requirements.txt
      pip3 install -r .github/workflows/common_libraries.txt  # for samples

    - name: Run test (1)
      run: python3 verify/tester_01.py

    - name: Run test (2)
      run: python3 verify/tester_02.py

    - name: Run test (3)
      run: python3 verify/tester_03.py

    - name: Run test (4)
      run: python3 verify/tester_04.py
